<a href="https://colab.research.google.com/github/akhilesh2009/Exploring-the-Titanic-Dataset/blob/main/Exploring_the_Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Study Titanic passengers to find what factors improved survival odds.**

In [34]:
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
train = pd.read_csv("train.csv")

In [36]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [37]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [38]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [39]:
train.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [40]:
print(train["Survived"].value_counts()[1])

342

**Survival by Gender**

In [41]:
survival_by_gender = train.groupby("Sex")["Survived"].sum()
survival_by_gender

Sex
female    233
male      109
Name: Survived, dtype: int64

Number of Females Survived

In [42]:
females_survive = survival_by_gender["female"]
print(f"Number of females survived: {females_survive}")

Number of females survived: 233

Number of males Survived

In [43]:
males_survives = survival_by_gender["male"]
print(f"Number of males survived: {males_survives}")

Number of males survived: 109

**Females have higher rate of survival then males**

Total number of Passengers

In [44]:
total_passengers_survive = (males_survives + females_survive)
print(total_passengers_survive)

342

Percent of Males Survived

In [45]:
percent_males_survived = (males_survives / total_passengers_survive) * 100
print(percent_males_survived)

31.871345029239766

Percent of Females Survived

In [46]:
percent_females_survived = (females_survive / total_passengers_survive) * 100
print(percent_females_survived)

68.12865497076024

**Survival rate by Pclass**

In [47]:
survival_by_class = train.groupby("Pclass")["Survived"].sum()
survival_by_class

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

Number of survived passenger from Pclass 1

In [48]:
survive_class_1 = survival_by_class[1]
survive_class_1

np.int64(136)

Number of survived passenger from Pclass 2

In [49]:
survive_class_2 = survival_by_class[2]
survive_class_2

np.int64(87)

Number of survived passenger from Pclass 3

In [50]:
survive_class_3 = survival_by_class[3]
survive_class_3

np.int64(119)

Percent of survived passenger from Pclass 1

In [51]:
percent_class1_survive = (survive_class_1 / total_passengers_survive) * 100
percent_class1_survive

np.float64(39.76608187134503)

Percent of survived passenger from Pclass 2

In [52]:
percent_class2_survive = (survive_class_2 / total_passengers_survive) * 100
percent_class2_survive

np.float64(25.438596491228072)

Percent of survived passenger from Pclass 3

In [53]:
percent_class3_survive = (survive_class_3 / total_passengers_survive) * 100
percent_class3_survive

np.float64(34.7953216374269)

**Survival rate by Age group**

Age column

In [54]:
train["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

minimum age

In [55]:
train["Age"].min()

0.42

maximum age

In [56]:
train["Age"].max()

80.0

In [57]:
age_survived = train.groupby("Age")["Survived"].sum()
age_survived

Age
0.42     1
0.67     1
0.75     2
0.83     2
0.92     1
        ..
70.00    0
70.50    0
71.00    0
74.00    0
80.00    1
Name: Survived, Length: 88, dtype: int64

Survial rate of Childs

In [62]:
for child_survived in age_survived[0:12]:
  print(child_survived)

1
1
2
2
1
5
3
5
7
4
2
1
2
2
0
1
1

/tmp/ipykernel_1819/2770082776.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  for child_survived in age_survived[0:12]:

In [63]:
age_survived[0:12].sum()

/tmp/ipykernel_1819/1757173844.py:1: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  age_survived[0:12].sum()

np.int64(40)